name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: ArtemSerebrennkov/buildozer-action@v1
        with:
          command: buildozer android debug
          # Bu satır robotun senin yerine 'evet' demesini sağlar
          buildozer_version: master
        env:
          # Android lisanslarını otomatik onaylar
          ACCEPT_SDK_LICENSE: "yes"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: HesapMakinesiAPK
          path: bin/*.apk
