name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # En güncel versiyon

      - name: Build with Buildozer
        uses: ArtemSerebrennkov/buildozer-action@v1 # Büyük/küçük harf düzeltildi
        with:
          buildozer_version: master
          command: buildozer android debug
          repository_read_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK
        uses: actions/upload-artifact@v4 # Hatanın çözümü: v2 yerine v4 kullanıyoruz
        with:
          name: HesapMakinesiAPK
          path: bin/*.apk
