name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Java Kur
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Sistem Hazırlığı
        run: |
          sudo apt update
          sudo apt install -y build-essential git zip unzip \
          libffi-dev libssl-dev libtool pkg-config autoconf automake gettext

      - name: Android SDK Kur
        uses: android-actions/setup-android@v3

      - name: SDK 31 ve NDK 23 Kur
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-31"
          sdkmanager "build-tools;31.0.0"
          sdkmanager "ndk;23.1.7779620"

      - name: Buildozer Kur
        run: |
          pip install --upgrade pip
          pip install buildozer cython==0.29.33

      - name: Clean Buildozer
        run: rm -rf .buildozer

      - name: APK Build
        run: |
          export APP_ANDROID_ACCEPT_SDK_LICENSE=1
          buildozer android debug

      - name: APK Yükle
        uses: actions/upload-artifact@v4
        with:
          name: ProHesap
