name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Python 3.12 bazen bu tip C derlemelerinde sorun çıkarıyor, 3.11 çok daha stabil.
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Derleme Araclarini Yukle
        run: |
          sudo apt update
          sudo apt install -y build-essential git python3-dev libffi-dev libssl-dev \
          libtool pkg-config autoconf automake gettext libltdl-dev m4 perl \
          libtool-bin zip unzip cmake

      - name: Buildozer ve Cython Hazirligi
        run: |
          pip install --upgrade pip
          pip install --user buildozer cython==0.29.33
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: APK Uretimini Baslat
        run: |
          # Lisans onaylarını ve NDK ayarlarını sisteme tanıtıyoruz
          export APP_ANDROID_ACCEPT_SDK_LICENSE=1
          buildozer android debug
        
      - name: APK Dosyasini Yukle
        uses: actions/upload-artifact@v4
        with:
          name: HesapMakinesi-Final-APK
          path: bin/*.apk
