name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sistem Hazirligi
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git python3 python3-dev \
          libffi-dev libssl-dev libtool pkg-config autoconf automake gettext

      - name: Buildozer ve Cython Kurulumu
        run: |
          pip3 install --user buildozer cython==0.29.33
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: APK Uretimini Baslat
        run: |
          # Lisanslari otomatik kabul eden çevre değişkeni
          export APP_ANDROID_ACCEPT_SDK_LICENSE=1
          buildozer android debug
        
      - name: APK Dosyasini Yukle
        uses: actions/upload-artifact@v4
        with:
          name: HesapMakinesiAPK
          path: bin/*.apk
